<a href="https://colab.research.google.com/github/JV456/PyTorch/blob/main/CreatingTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy
import pandas
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR = torch.tensor([[[7,8,9,0],
                        [4,5,6,9],
                        [3,2,1,7]]])
TENSOR

tensor([[[7, 8, 9, 0],
         [4, 5, 6, 9],
         [3, 2, 1, 7]]])

In [20]:
TENSOR.shape

torch.Size([1, 3, 4])

### Random Tensors

In [21]:
random_tensor = torch.rand(5,4)
random_tensor

tensor([[0.0884, 0.2128, 0.8719, 0.9910],
        [0.3968, 0.5995, 0.3538, 0.5187],
        [0.0403, 0.4948, 0.2683, 0.3699],
        [0.9055, 0.9550, 0.9766, 0.4845],
        [0.7240, 0.9977, 0.8376, 0.7692]])

In [22]:
random_tensor.ndim

2

In [23]:
# creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# zeros and ones

In [2]:
# creating a tensor od all zeros
zeros = torch.zeros(size=(5,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# create a tensor of all one
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

Creating range of tensors and tensors-like

In [28]:
torch.range(0,10)

<ipython-input-28-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
zero_to_fifty = torch.arange(start=0, end=50, step=12)
zero_to_fifty

tensor([ 0, 12, 24, 36, 48])

In [36]:
# creating tensors like
ten_zeros = torch.zeros_like(input=(one_to_ten))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
ten_ones = torch.ones_like(input=(one_to_ten))
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])