<a href="https://colab.research.google.com/github/JV456/PyTorch/blob/main/Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy

# Create a random tensor with shape (7, 7)

In [3]:
tensor_A = torch.rand([7,7])
tensor_A , tensor_A.shape

(tensor([[0.4325, 0.4871, 0.9078, 0.4588, 0.8141, 0.7564, 0.8523],
         [0.1486, 0.5745, 0.2304, 0.9269, 0.1715, 0.7905, 0.7384],
         [0.3113, 0.1003, 0.6773, 0.7135, 0.8462, 0.1095, 0.4506],
         [0.6268, 0.2361, 0.1701, 0.2820, 0.2160, 0.4581, 0.6371],
         [0.7663, 0.1452, 0.5823, 0.8949, 0.1278, 0.5579, 0.9786],
         [0.2018, 0.7968, 0.7169, 0.4489, 0.8943, 0.9586, 0.2251],
         [0.0045, 0.0439, 0.3837, 0.9978, 0.2865, 0.6262, 0.5339]]),
 torch.Size([7, 7]))

# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7).

In [4]:
tensor_B = torch.rand(1,7)
tensor_B = tensor_B.T
tensor_C = torch.matmul(tensor_A,tensor_B)
tensor_C , tensor_C.shape

(tensor([[2.3065],
         [1.6868],
         [1.7287],
         [1.1924],
         [2.0425],
         [1.7211],
         [1.4530]]),
 torch.Size([7, 1]))

# Set the random seed to 0 and do exercises 2 & 3 over again.

In [5]:
torch.manual_seed(0)

X = torch.rand(1,7)
Y = torch.rand(7,7)

Z = torch.matmul(X,Y.T)
Z , Z.shape


(tensor([[1.1173, 1.2741, 1.6838, 0.8279, 1.0347, 1.2498, 1.8542]]),
 torch.Size([1, 7]))

In [6]:
torch.cuda.manual_seed(1234)

# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors.

In [7]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

A = torch.rand(2,3).to(device)
B = torch.rand(2,3).to(device)

A , B


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

#  Perform a matrix multiplication on the tensors you created in 6

In [8]:
C = torch.matmul(A, B.T)
C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

# Find the maximum and minimum values of the output of 7.

In [11]:
min = torch.min(C)
print(f"min: {min}")
max = torch.max(C)
print(f"max: {max}")

min: 0.3647301495075226
max: 0.5617256760597229


In [12]:
min , max

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

# Find the maximum and minimum index values of the output of 7

In [13]:
index_min = torch.argmin(C)
index_max = torch.argmax(C)

index_min , index_max

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [16]:
torch.manual_seed(7)

random_tensor = torch.rand(size=(1,1,1,10))

random_tensor1 = random_tensor.squeeze()

print(random_tensor, random_tensor.shape)
print(random_tensor1, random_tensor1.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
