<a href="https://colab.research.google.com/github/JV456/PyTorch/blob/main/ManipulatingTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy
import pandas
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [2]:
tensor = torch.tensor([4,5,6])
tensor + 10

tensor([14, 15, 16])

In [3]:
tensor * 10

tensor([40, 50, 60])

In [5]:
tensor - 10

tensor([30, 40, 50])

In [6]:
torch.multiply(tensor,10)

tensor([400, 500, 600])

In [7]:
torch.add(tensor,50)

tensor([ 90, 100, 110])

## matrix multiplication

In [10]:
# element wise multiplication

print(tensor, "*" , tensor)
print(f"Equals: {tensor*tensor}")

tensor([40, 50, 60]) * tensor([40, 50, 60])
Equals: tensor([1600, 2500, 3600])


In [11]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(7700)

In [12]:
40*40 + 50*50 + 60*60

7700

In [15]:
tensor = torch.rand(4,5).shape
tensor

torch.Size([4, 5])

In [16]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))  # inner dimensions should match here -> 2,2

tensor([[0.0117, 0.7371, 0.7620],
        [0.0215, 0.4977, 0.3637],
        [0.0450, 0.8924, 0.5795]])

In [19]:
torch.matmul(torch.rand(4,5), torch.rand(5,5)) # the result will be on the basis of outer dimensions

tensor([[1.7039, 1.7632, 1.8717, 0.9654, 1.9224],
        [1.4341, 2.0331, 1.6265, 1.4195, 2.3279],
        [2.4546, 2.9134, 2.4275, 1.6862, 2.6514],
        [1.5640, 1.9959, 1.5492, 1.2003, 2.3416]])

In [25]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [28]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [30]:
# to fix our tensor shapes issues, we can manipulate the shape of one of tensor using a transpose

tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [31]:
# now we will not encounter the shape error

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min , max , sum , mean , etc (tensor aggregation)

In [34]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [38]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [40]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [41]:
# to find the mean - torch.mean() requires a tensor of float32 datatype to work
x.dtype

torch.int64

In [43]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [45]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [46]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
x.argmin() # returns the index position of target tensor where the minimum value occurs

tensor(0)

In [54]:
y = torch.arange(2,100,20)
y

tensor([ 2, 22, 42, 62, 82])

In [55]:
y.argmin()

tensor(0)

In [58]:
y.argmax(), x.argmax(), x[9]

(tensor(4), tensor(9), tensor(90))

## reshaping, stacking, squeezing and unsqueezing tensors

In [60]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [63]:
# reshape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [66]:
y = torch.arange(1.,13.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [67]:
y_reshaped = y.reshape(3,4)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [68]:
y_reshaped = y.reshape(6,2)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [69]:
# change the view
z = x.view(1,9)
z, z.shape
# changing the z changes x (because a view of a tensor shares the same memory as the original input)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [70]:
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [72]:
# stack tensors on the top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [73]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [74]:
# torch.squeeze()
x_reshaped


tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [82]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [84]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

## indexing (selecting data from tensors)

In [85]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [86]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
x[0][0]

tensor([1, 2, 3])

In [89]:
x[0][0][0]

tensor(1)

In [90]:
x[0][0][1]

tensor(2)

In [91]:
x[0][1][1]

tensor(5)

In [92]:
x[0][2][2]

tensor(9)

In [93]:
# we can also use
x[: , 0]

tensor([[1, 2, 3]])

In [94]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [96]:
x[:, 2, :]

tensor([[7, 8, 9]])