<a href="https://colab.research.google.com/github/JV456/PyTorch/blob/main/PytorchTensors%26NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy to Tensor

In [1]:
import torch
import numpy as np

In [2]:
array = np.arange(1.0,7.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6.]),
 tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64))

In [3]:
# when we change the value of array, it will not change the value of tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64))

# Tensor to Numpy

In [7]:
# tensor to numpy

tensor = torch.ones(2)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1.]), array([1., 1.], dtype=float32))

In [9]:
#  when we change the value of tensor, it will not change the value of numpy_tensor
tensor = tensor + 1
tensor , numpy_tensor

(tensor([3., 3.]), array([1., 1.], dtype=float32))

#Pytorch Reproducibility (trying to take random out of random)

In [10]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7148, 0.4953, 0.5274, 0.4790],
        [0.4147, 0.0825, 0.5423, 0.4389],
        [0.6587, 0.9259, 0.6289, 0.7041]])
tensor([[0.4222, 0.3656, 0.1930, 0.2838],
        [0.4984, 0.1964, 0.0230, 0.2826],
        [0.8324, 0.3408, 0.4176, 0.3400]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [15]:
# lets make some random but reproducible tensors

# setting the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
